version: '2.3'

services:
  vllm:
    image: vllm/vllm-openai:latest
    volumes:
      - ${HF_HOME:-~/.cache/huggingface}:/root/.cache/huggingface
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    command: --model ${MODEL:-google/gemma-2-9b-it} --gpu-memory-utilization ${GPU_MEMORY_UTILIZATION:-1.0} --tensor-parallel-size ${TENSOR_PARALLEL_SIZE:-4} --host 0.0.0.0 --port 8000
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - vllm_network

networks:
  vllm_network:
    driver: bridge 