version: '2.3'

services:
  vllm:
    image: vllm/vllm-openai:latest
    volumes:
      - ${HF_HOME:-~/.cache/huggingface}:/root/.cache/huggingface
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    # Install the latest transformers from GitHub and run vLLM with limited max sequence length
    entrypoint: >
      /bin/bash -c "
      pip install git+https://github.com/huggingface/transformers.git &&
      python -m vllm.entrypoints.openai.api_server --model google/gemma-3-4b-it --gpu-memory-utilization ${GPU_MEMORY_UTILIZATION:-0.9} --tensor-parallel-size 1 --max-model-len 8192 --host 0.0.0.0 --port 8000
      "
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - vllm_network

networks:
  vllm_network:
    driver: bridge 